[project]
name = "smp-repo-server"
version = "0.1.0"
requires-python = ">=3.10"
dependencies = [
  "fastapi>=0.110",
  "uvicorn[standard]>=0.27",
  "pydantic>=2.6",
  "python-multipart>=0.0.9",
  "packaging>=24.0",
  "smpclient>=6.0.0",
]

[tool.uvicorn]
factory = false
